### ISSUE TITLE
JOSS - Test coverage

### ISSUE THREAD

**Issue by clemaitre58** [UniNE-CHYN/mmappickle#14]
Hi,
Could you add some test to verify the support of 'nt' in source : utils.py 
https://coveralls.io/builds/16773337/source?filename=mmappickle/utils.py

**Comment by lfasnacht** [comment]
Actually, it is covered by the tests (running on AppVeyor), but coveralls doesn't see it because the coverage is uploaded by travis-ci on Linux.

It seems not possible to sum the coverage as far as I know (and according to https://github.com/lemurheavy/coveralls-public/issues/544).

**Comment by clemaitre58** [comment]
Could you provide a AppVeyor results?

**Comment by lfasnacht** [comment]
I tried to add the coverage to appveyor.yml, the output should appear in the build logs at appveyor (it's awfully slow): 

https://ci.appveyor.com/project/lfasnacht/mmappickle/

**Comment by lfasnacht** [comment]
It worked:

```----------- coverage: platform win32, python 3.6.4-final-0 -----------
Name                              Stmts   Miss  Cover   Missing
---------------------------------------------------------------
mmappickle\__init__.py                3      0   100%
mmappickle\_version.py                1      0   100%
mmappickle\dict.py                  459      6    99%   820-826
mmappickle\picklers\__init__.py       9      2    78%   10-12
mmappickle\picklers\base.py          84      6    93%   27, 33, 38, 46, 79-80
mmappickle\picklers\numpy.py        109      7    94%   41, 81, 83, 87, 107, 109, 116
mmappickle\stubs\__init__.py          7      2    71%   7-9
mmappickle\stubs\numpy.py            12      0   100%
mmappickle\utils.py                  66     13    80%   14-18, 30-34, 72-77, 84
---------------------------------------------------------------
TOTAL                               750     36    95%
```

**Comment by clemaitre58** [comment]
Ok great!
