### ISSUE TITLE
JOSS - rework setup.py

### ISSUE THREAD

**Issue by glemaitre** [UniNE-CHYN/mmappickle#6]
The `setup.py` is not really nice. I would advice to use a template as [here](https://github.com/uwescience/shablona/blob/master/setup.py)

**Comment by glemaitre** [comment]
You should restrict the install to python 3 only since this is not python 2 compatible:
https://packaging.python.org/tutorials/distributing-packages/#python-requires

**Comment by glemaitre** [comment]
Improve the setup as well such that there information in the PyPi webpage.

**Comment by lfasnacht** [comment]
I improved `setup.py`. I didn't follow the logic in the `shablona` project, as I'm not fond of it. I used some inspiration from [the pypa sample `setup.py`](https://github.com/pypa/sampleproject/blob/master/setup.py).

Is this file "nice enough"? Or do you see additional improvements?

**Comment by glemaitre** [comment]
It seems almost good. Could you take care about the PEP8.
Also it has to be check, for the long description I don't remember if you can give markdown or it needs to be rst to render properly on PyPi. But this point does not need to be addressed, you will see at the release time.

**Comment by lfasnacht** [comment]
It [should work](https://stackoverflow.com/a/26737258).

PEP8 is in my to-do list, but I'll do the code styling all at once, I'm working on the coverage at present.
