### ISSUE TITLE
JOSS - Installation

### ISSUE THREAD

**Issue by glemaitre** [UniNE-CHYN/mmappickle#7]
### Install from PyPi

You should not ask for `pip3`

### Install from source

Mention the dependencies before the install. You can mention that they are optional as well.

```
git clone https://github.com/UniNE-CHYN/mmappickle
cd mmappickle
sudo python3 setup.py install
```

This is a bad practice to show install using sudo. Also you should use pip to install as well from source

```
pip install .
```

or in developer mode

```
pip install -e .
```

**Comment by glemaitre** [comment]
I think that I would put it in the same section: you need to show how to test the code. I would make a subsection in the install.

**Comment by lfasnacht** [comment]
I improved the [Installation](http://mmappickle.readthedocs.io/en/latest/install.html) page, unfortunately it seems that a lot of Linux distributions use `pip3`/`pip2`, with `pip` defaulting to Python version 2.

Does this seems ok to you?

**Comment by lfasnacht** [comment]
Thanks!
